### ISSUE TITLE
@conda-forge-admin, please update version

### ISSUE THREAD

**Issue by alanhdu** [conda-forge/pywavelets-feedstock#54]

**Comment by rgommers** [comment]
Could you add some context here @alanhdu, why is the rebuild needed?

**Comment by ocefpaf** [comment]
> Could you add some context here @alanhdu, why is the rebuild needed?

That command is not to rebuild but to request the latest version. I guess the bot failed to pull it here. Investigating...

**Comment by alanhdu** [comment]
> That command is not to rebuild but to request the latest version. I guess the bot failed to pull it here. Investigating...


Yeah, that's exactly it. I was hoping to pull in PyWavelets 1.6 -- thanks for taking the conda-forge release work on!
